{% if values.networkingEnabled | bool %}
---
apiVersion: gcp.project-planton.org/v1
kind: GcpVpc
metadata:
  name: "{{ values.vpc_name }}"
  group: network
spec:
  networkName: "{{ values.vpc_name }}"
  projectId: 
    value: "{{ values.gcp_project_id }}"
  autoCreateSubnetworks: false
  routingMode: REGIONAL
---
apiVersion: gcp.project-planton.org/v1
kind: GcpSubnetwork
metadata:
  name: "{{ values.vpc_name }}-subnet"
  group: network
  relationships:
    - kind: GcpVpc
      name: "{{ values.vpc_name }}"
      type: runs_on
spec:
  subnetworkName: "{{ values.vpc_name }}-subnet"
  projectId: 
    value: "{{ values.gcp_project_id }}"
  vpcSelfLink:
    valueFrom:
      kind: GcpVpc
      name: "{{ values.vpc_name }}"
      fieldPath: status.outputs.network_self_link
  region: "{{ values.gcp_region }}"
  ipCidrRange: "{{ values.subnet_cidr }}"
  privateIpGoogleAccess: true
---
apiVersion: gcp.project-planton.org/v1
kind: GcpRouterNat
metadata:
  name: "{{ values.vpc_name }}-router-nat"
  group: network
  relationships:
    - kind: GcpVpc
      name: "{{ values.vpc_name }}"
      type: runs_on
spec:
  projectId: 
    value: "{{ values.gcp_project_id }}"
  routerName: "{{ values.vpc_name }}-router"
  natName: "{{ values.vpc_name }}-nat"
  vpcSelfLink:
    valueFrom:
      kind: GcpVpc
      name: "{{ values.vpc_name }}"
      fieldPath: status.outputs.network_self_link
  region: "{{ values.gcp_region }}"
{% endif %}

