{% if values.serviceAccountEnabled | bool %}
---
apiVersion: gcp.project-planton.org/v1
kind: GcpServiceAccount
metadata:
  name: "{{ values.service_account_id }}"
spec:
  projectId:
    value: "{{ values.gcp_project_id }}"
  orgId: "{{ values.gcp_region }}"
  serviceAccountId: "{{ values.service_account_id }}"
  createKey: true
  # NOTE: IAM permissions (e.g., Storage Admin) must be granted separately
{% endif %}

